apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      tolerations:
      - key: qishon
        operator: Exists
        effect: NoSchedule
      containers:
        - name: mysql-exporter
          env:
          - name: DATA_SOURCE_NAME
            value: root:mysql8888@(1.1.20.80:33306)/
          image: prom/mysqld-exporter
          imagePullPolicy: Always
          name: mysql-exporter
          ports:
          - containerPort: 9104
            protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: 20work03
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-svc
  labels:
    k8s-app: mysql-exporter
  namespace: monitoring
spec:
  ports:
    - port: 9104
      targetPort: 9104
      protocol: TCP
      name: http-mysql-exporter
