apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
  namespace: monitoring
  labels:
    pv: nfs-pv2
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.130.44.20
    path: "/test/mysql-nfs01"
