apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6IAogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiAgInNtdHBfc21hcnRob3N0IjogInNtdHAuZXhtYWlsLnFxLmNvbTo0NjUiCiAgInNtdHBfZnJvbSI6ICJqaWUueWFuZ0BxaXNob24uY29tIgogICJzbXRwX2F1dGhfdXNlcm5hbWUiOiAiamllLnlhbmdAcWlzaG9uLmNvbSIKICAic210cF9hdXRoX3Bhc3N3b3JkIjogIjEyMzQ1NllqIgogICJzbXRwX3JlcXVpcmVfdGxzIjogZmFsc2UKInJlY2VpdmVycyI6IAotICJuYW1lIjogImVtYWlsIgogICJlbWFpbF9jb25maWdzIjogCiAgIC0gInRvIjogInh4eHhAcXEuY29tIiAKICAgICAiaHRtbCI6ICd7eyB0ZW1wbGF0ZSAiZW1haWwuZGVmYXVsdC5odG1sIiAuIH19JwogICAgICJoZWFkZXJzIjogeyBTdWJqZWN0OiAiW1dBUk5dIOaKpeitpumCruS7tiJ9CiAgIndlYmhvb2tfY29uZmlncyI6IAogICAtICJ1cmwiOiAiaHR0cDovLzEuMS4yLjUwOjgwODAvZGluZ3RhbGsvbm9kZS9zZW5kIgoicm91dGUiOiAKICAiZ3JvdXBfYnkiOiAKICAtICJzZXZlcml0eSIKICAiZ3JvdXBfaW50ZXJ2YWwiOiAiMTBtIgogICJncm91cF93YWl0IjogIjMwcyIKICAicmVjZWl2ZXIiOiAiZW1haWwiCiAgInJlcGVhdF9pbnRlcnZhbCI6ICIyMG0i
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
