apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        args: 
        - --redis.addr=redis-file-system.business.svc.cluster.local:6379,redis-gateway.business.svc.cluster.local:6379,redis-iss.business.svc.cluster.local:6379,redis-security.business.svc.cluster.local:6379,redis-short-message.business.svc.cluster.local:6379,redis-wechat.business.svc.cluster.local:6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9121

---


---

apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-svc
  namespace: monitoring
  labels:
    k8s-app: redis-exporter
spec:
  ports:
    - port: 9121
      protocol: TCP
      targetPort: 9121
      name: https
  selector:
    app: redis-exporter

